apiVersion: plural.sh/v1alpha1
kind: Context
spec:
  bundles:
  - repository: airflow
    name: gcp-airflow
  - repository: console
    name: console-gcp
  configuration:
    airflow:
      adminEmail: yirenlu92@gmail.com
      adminFirst: Yiren
      adminLast: Lu
      adminUsername: yirenlu
      airflowBucket: ren-plural-2-airflow-bucket
      branchName: master
      dagRepo: ren-plural-dag-repo
      hostname: airflow.tryunitofwork.onplural.sh
    bootstrap:
      dns_domain: tryunitofwork.onplural.sh
      ownerEmail: yirenlu92@gmail.com
      pluralDns: true
      txt_owner: ren-plural-3
      vpc_name: ren-plural-cloud-3
    console:
      admin_email: yirenlu92@gmail.com
      admin_name: Yiren
      console_dns: console.tryunitofwork.onplural.sh
      git_email: yirenlu13@gmail.com
      git_user: yirenlu92
    monitoring: {}
    postgres:
      wal_bucket: ren-plural-2-wal-archives
