apiVersion: plural.sh/v1alpha1
kind: Context
spec:
  bundles:
  - repository: airflow
    name: gcp-airflow
  configuration:
    airflow:
      adminEmail: yirenlu92@gmail.com
      adminFirst: Yiren
      adminLast: Lu
      adminUsername: yirenlu
      airflowBucket: plural-airflow-logs
      branchName: master
      dagRepo: plural-airflow-dag
      hostname: airflow.tryunitofwork.onplural.sh
    bootstrap:
      dns_domain: tryunitofwork.onplural.sh
      ownerEmail: yirenlu92@gmail.com
      pluralDns: true
      vpc_name: plural
    postgres:
      wal_bucket: plural-wal-archives
