apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: console
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: console
    version: 0.5.45
    description: plural admin console
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/4d9e07ec-fd50-4bc2-80c5-55a8e29c8997/console-logo.png?v=63791948433
    
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/4d9e07ec-fd50-4bc2-80c5-55a8e29c8997/console-white.png?v=63791948433
    
